name: Run main.py

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 3am
  
    workflow_dispatch:

jobs:
  CreateFuboPSSHs:
    runs-on:
      - self-hosted
      - macOS
    steps:
      - uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Install requirements packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run PSSH script # run main.py
        run: python3 fubo_pssh.py

      # Reference the commit_and_push job after your steps are completed
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_PAT_TOKEN }}
          branch: main

  CreateFuboKeys:
    runs-on:
      - self-hosted
      - macOS
    needs: CreateFuboPSSHs
    steps:
      - name: Run Keys script
        run: python3 fubo_keys.py

      # Reference the commit_and_push job after your steps are completed
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_PAT_TOKEN }}
          branch: main

  CreateFuboURLs:
    runs-on:
      - self-hosted
      - macOS
    needs: CreateFuboKeys
    steps:
      - name: Run Main script
        run: python3 main.py

      # Reference the commit_and_push job after your steps are completed
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_PAT_TOKEN }}
          branch: main

  XAccelUpload:
    runs-on:
      - self-hosted
      - macOS
    needs: CreateFuboURLs
    steps:
      - name: Run Xaccel script
        run: python3 XAccel_fubo.py

      # Reference the commit_and_push job after your steps are completed
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_PAT_TOKEN }}
          branch: main

  XAccelStartStop:
    runs-on:
      - self-hosted
      - macOS
    needs: XAccelUpload
    steps:
      - name: Run Xaccel Start Stop script
        run: python3 XAccel+start_stop_fubo.py

      # Reference the commit_and_push job after your steps are completed
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_PAT_TOKEN }}
          branch: main
